package alarmsystem;


/**
* alarmsystem/Alarm.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/alarmsystem/Alarm.idl
* Thursday, 18 September, 2025 11:33:50 AM IST
*/

public interface Alarm extends AlarmOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
}
