package alarmsystem;


/**
* alarmsystem/AlarmHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/alarmsystem/Alarm.idl
* Thursday, 18 September, 2025 12:28:43 PM IST
*/

abstract public class AlarmHelper
{
  private static String  _id = "IDL:alarmsystem/Alarm:1.0";

  public static void insert (org.omg.CORBA.Any a, alarmsystem.Alarm that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static alarmsystem.Alarm extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (alarmsystem.AlarmHelper.id (), "Alarm");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static alarmsystem.Alarm read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AlarmStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, alarmsystem.Alarm value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static alarmsystem.Alarm narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof alarmsystem.Alarm)
      return (alarmsystem.Alarm)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      alarmsystem._AlarmStub stub = new alarmsystem._AlarmStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static alarmsystem.Alarm unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof alarmsystem.Alarm)
      return (alarmsystem.Alarm)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      alarmsystem._AlarmStub stub = new alarmsystem._AlarmStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
