package alarmsystem;


/**
* alarmsystem/AlarmOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/alarmsystem/Alarm.idl
* Thursday, 18 September, 2025 12:28:43 PM IST
*/

public interface AlarmOperations 
{

  // Returns the corrective action the operator must follow to fix the problem
  String getAction ();

  // Returns unique alarm identifier in format FF_FM (e.g., MOUNT_001)
  String getAlarmId ();

  // Returns alarm priority: 0=Critical(red), 1=Major(orange), 2=Minor(yellow), 3=Warning(light yellow)
  int getPriority ();

  // Returns alarm activation state: ACTIVE, INACTIVE, TERMINATE
  String getStatus ();

  // Returns URL pointing to detailed documentation and procedures
  String getHelpURL ();

  // ALMA-compliant method: retrieves alarm data by ID, returns JSON with full alarm details
  String getAlarmById (String id);
} // interface AlarmOperations
