package alarmsystem;

/**
* alarmsystem/AlarmHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/alarmsystem/Alarm.idl
* Thursday, 18 September, 2025 12:28:43 PM IST
*/

public final class AlarmHolder implements org.omg.CORBA.portable.Streamable
{
  public alarmsystem.Alarm value = null;

  public AlarmHolder ()
  {
  }

  public AlarmHolder (alarmsystem.Alarm initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = alarmsystem.AlarmHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    alarmsystem.AlarmHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return alarmsystem.AlarmHelper.type ();
  }

}
