package alarmsystem;


/**
* alarmsystem/AlarmPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/alarmsystem/Alarm.idl
* Thursday, 18 September, 2025 11:33:50 AM IST
*/

public abstract class AlarmPOA extends org.omg.PortableServer.Servant
 implements alarmsystem.AlarmOperations, org.omg.CORBA.portable.InvokeHandler
{

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getAction", new java.lang.Integer (0));
    _methods.put ("getAlarmId", new java.lang.Integer (1));
    _methods.put ("getPriority", new java.lang.Integer (2));
    _methods.put ("getStatus", new java.lang.Integer (3));
    _methods.put ("getHelpURL", new java.lang.Integer (4));
    _methods.put ("getAlarmById", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:
       {
         String $result = null;
         $result = this.getAction ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // alarmsystem/Alarm/getAlarmId
       {
         String $result = null;
         $result = this.getAlarmId ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // alarmsystem/Alarm/getPriority
       {
         int $result = (int)0;
         $result = this.getPriority ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // alarmsystem/Alarm/getStatus
       {
         String $result = null;
         $result = this.getStatus ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // alarmsystem/Alarm/getHelpURL
       {
         String $result = null;
         $result = this.getHelpURL ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  // ALMA-style method - adding the one you asked about
       case 5:  // alarmsystem/Alarm/getAlarmById
       {
         String id = in.read_string ();
         String $result = null;
         $result = this.getAlarmById (id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:alarmsystem/Alarm:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Alarm _this() 
  {
    return AlarmHelper.narrow(
    super._this_object());
  }

  public Alarm _this(org.omg.CORBA.ORB orb) 
  {
    return AlarmHelper.narrow(
    super._this_object(orb));
  }


} // class AlarmPOA
